import smtplib
import datetime
import os
from email.mime.text import MIMEText
from email.header import Header
from email.utils import parseaddr, formataddr
import logging

def _format_addr(s: str) -> str:
    """
    Format the email addresses with a name.
    """
    name, addr = parseaddr(s)
    return formataddr((Header(name, 'utf-8').encode(), addr))

def read_html_file(file_path: str) -> str:
    """
    Read the content of an HTML file.
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            return file.read()
    except FileNotFoundError:
        logging.warning(f"File not found: {file_path}")
        return ""

def send_daily_email():
    """
    Construct and send the daily email with Arxiv updates.
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    from_addr = os.environ.get("FROM_ADDR")
    password = os.environ.get("PASSWORD")  # App-specific password
    to_addr_str = os.environ.get("TO_ADDR")
    to_addr = [to_addr_str] if to_addr_str else []
    smtp_server = "smtp.qq.com"  # SMTP server for QQ mail

    if not from_addr or not password or not to_addr:
        logging.error("Email credentials or recipient missing. Skipping email.")
        return

    # Paths may need to be adjusted based on the execution environment
    html_path_en = '/home/runner/work/Arxiv_GPT_Assistant/Arxiv_GPT_Assistant/dist/en/index.html'
    html_path_zh = '/home/runner/work/Arxiv_GPT_Assistant/Arxiv_GPT_Assistant/dist/zh/index.html'
    
    html_content_1 = read_html_file(html_path_en)
    html_content_2 = read_html_file(html_path_zh)

    combined_html_content = f'''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f6f8fa;
            }}
            .email-container {{
                background-color: #ffffff;
                padding: 30px;
                border-radius: 8px;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            }}
            h1, h2, h3 {{
                color: #24292e;
            }}
            .divider {{
                border-top: 2px solid #e1e4e8;
                margin: 40px 0;
            }}
            /* Additional styles are inherited from formatters.py inline styles */
        </style>
    </head>
    <body>
        <div class="email-container">
            <div style="text-align: center; margin-bottom: 30px;">
                <h1>📰 ArXiv Daily AI Newsletter</h1>
                <p style="color: #586069;">{now}</p>
            </div>
            
            <div class="english-section">
                {html_content_1}
            </div>
            
            <div class="divider"></div>
            
            <div class="chinese-section">
                <h2 style="text-align: center; color: #d73a49;">🇨🇳 中文翻译版本 (Chinese Translation)</h2>
                {html_content_2}
            </div>
            
            <div style="text-align: center; margin-top: 50px; font-size: 12px; color: #959da5;">
                <p>This email was automatically generated by ArXiv GPT Assistant.</p>
                <p>Powered by GitHub Actions & Large Language Models.</p>
            </div>
        </div>
    </body>
    </html>
    '''

    msg = MIMEText(combined_html_content, 'html', 'utf-8')
    msg['From'] = _format_addr(f'Arxiv_GPT_Assistant <{from_addr}>')
    msg['To'] = _format_addr(f'Arxiv_GPT_Assistant')
    msg['Subject'] = Header(f'ArXiv daily: {now}', 'utf-8').encode()

    try:
        server = smtplib.SMTP_SSL(smtp_server, 465)
        server.set_debuglevel(1)
        server.login(from_addr, password)
        server.sendmail(from_addr, to_addr, msg.as_string())
        logging.info("Email sent successfully!")
    except Exception as e:
        logging.error(f"An error occurred while sending email: {e}")
    finally:
        try:
            server.quit()
        except:
            pass

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    send_daily_email()
